HOST = "mongodb://localhost:27017/"
DATABASE_NAME = "HealthCV"
USERS_COLLECTION_NAME = "users"
GAMES_COLLECTION_NAME = "games"
KickAndCatchMatchRecord_COLLECTION_NAME = "kick_and_catch_match_records"
YogaImitation_COLLECTION_NAME = "yoga_imitation_match_records"
