HOST = "mongodb://localhost:27017/"
DATABASE_NAME = "HealthCV"
USERS_COLLECTION_NAME = "users"
GAMES_COLLECTION_NAME = "games"
WORKOUT_EXERCISE_COLLECTION_NAME = "workout_exercise"
KickAndCatchMatchRecord_COLLECTION_NAME = "kick_and_catch_match_records"
YogaImitation_COLLECTION_NAME = "yoga_imitation_match_records"
PushUpRecord_COLLECTION_NAME = "push_up_records"
